import { AuthStatus, INTEGRATION_AUTH_STATUS } from '@/types/custom';

export const INTEGRATION_UI_STATUS = {
  CONNECTED: 'CONNECTED',
  NEEDS_RECONNECTION: 'NEEDS_RECONNECTION',
  PROCESSING: 'PROCESSING',
  UNCONNECTED: 'UNCONNECTED'
} as const;

export type IntegrationUIStatus = (typeof INTEGRATION_UI_STATUS)[keyof typeof INTEGRATION_UI_STATUS];

export function mapAuthStatusToUIStatus(authStatus: AuthStatus): IntegrationUIStatus {
  switch (authStatus) {
    case INTEGRATION_AUTH_STATUS.OK:
    case INTEGRATION_AUTH_STATUS.CREATION_SUCCESS:
    case INTEGRATION_AUTH_STATUS.RECONNECTED:
    case INTEGRATION_AUTH_STATUS.SYNC_SUCCESS:
      return INTEGRATION_UI_STATUS.CONNECTED;
    case INTEGRATION_AUTH_STATUS.STOPPED:
    case INTEGRATION_AUTH_STATUS.CREDENTIALS:
    case INTEGRATION_AUTH_STATUS.ERROR:
      return INTEGRATION_UI_STATUS.NEEDS_RECONNECTION;
    case INTEGRATION_AUTH_STATUS.CONNECTING:
      return INTEGRATION_UI_STATUS.PROCESSING;
    case INTEGRATION_AUTH_STATUS.DELETED:
    default:
      return INTEGRATION_UI_STATUS.UNCONNECTED;
  }
}
