import Link from 'next/link';

import { Logo } from '@/components/marketing/logo';
import { ROUTES } from '@/lib/routes';

export default function Terms() {
  return (
    <div className='min-h-screen bg-white'>
      <div className='mx-auto max-w-4xl px-6 py-12'>
        <div className='mb-12'>
          <Link href={ROUTES.HOME}>
            <Logo />
          </Link>
        </div>

        <div className='space-y-8 text-gray-700'>
          <h1 className='mb-2 text-4xl font-bold'>Terms of Service</h1>
          <p className='text-gray-500'>Last Updated: July 1, 2025</p>

          <p className='mb-8'>
            Welcome to SuperLeader. These Terms of Service ("Terms") constitute a legally binding agreement between you
            ("User," "you") and SuperLeader Inc. ("SuperLeader," "we," "us"). By accessing or using the SuperLeader
            application, website, or services (collectively, the "Services"), you agree to be bound by these Terms. If
            you do not agree to these Terms, do not use the Services.
          </p>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>1. Description of Services</h2>
            <p>
              SuperLeader is an AI-powered relationship assistant designed to help entrepreneurs and professionals
              manage context around their contacts, recall key details, and follow up meaningfully. The platform
              integrates with third-party services and uses artificial intelligence to generate insights and assist with
              relationship management.
            </p>
          </section>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>2. Eligibility</h2>
            <p>
              There are no age or geographic restrictions for using SuperLeader. However, by accessing the Services, you
              represent and warrant that you have the legal capacity to enter into these Terms and are not prohibited
              from doing so by any applicable law or regulation.
            </p>
          </section>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>3. Account Registration and Access</h2>
            <p>
              You may create an account using your email and password or by authenticating through third-party OAuth
              providers such as Google, Apple, or Facebook. Multiple individuals, such as personal assistants or team
              members, may access the account on your behalf, provided such access is authorized by you.
            </p>
          </section>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>4. Ownership and Licenses</h2>
            <p>
              All content generated by the SuperLeader AI (including but not limited to notes, summaries, contact
              insights, and messages) is owned by you. However, by using the Services, you grant SuperLeader a
              perpetual, non-exclusive, royalty-free license to use, access, and analyze such content for the purposes
              of providing, improving, maintaining, and debugging the Services.
            </p>
          </section>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>5. Payments</h2>
            <p>
              Pricing for the Services may vary and is subject to change. Currently, there is no free trial or fixed
              subscription model, though one may be offered in the future. Payment processing is handled by third-party
              providers such as Stripe, BitPay Server, or Zaprite. By submitting payment information, you authorize
              SuperLeader and these third parties to charge your selected payment method.
            </p>
            <p className='mt-4'>SuperLeader does not currently support invoicing for enterprise or B2B accounts.</p>
          </section>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>6. Acceptable Use</h2>
            <p>
              Users agree to use the Services in compliance with all applicable laws. While no specific technical
              restrictions are imposed on behaviors such as scraping or automated spamming, such use is discouraged and
              may result in account suspension if deemed abusive or harmful to service integrity.
            </p>
          </section>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>7. Support and Availability</h2>
            <p>
              The Services are provided on an "as-is" and "as-available" basis. While we strive to maintain uptime and
              system stability, SuperLeader offers no guarantees on service availability or performance.
            </p>
            <p className='mt-4'>
              Support is available via email and scheduled calls. There are no guaranteed response times or business
              hours; support is assumed to be available 24/7 via email.
            </p>
          </section>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>8. Cancellation and Termination</h2>
            <p>
              You may cancel your account at any time by requesting termination. Upon cancellation, your data will be
              retained unless you explicitly request permanent deletion. SuperLeader reserves the right to suspend or
              terminate accounts for abuse, fraud, or other violations of these Terms.
            </p>
          </section>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>9. Governing Law and Dispute Resolution</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of Texas, United
              States, without regard to its conflict of laws principles.
            </p>
            <p className='mt-4'>
              All disputes arising under or relating to these Terms shall be resolved through binding arbitration,
              conducted in English and located in Texas. You agree to waive any right to participate in class actions or
              class-wide arbitration.
            </p>
          </section>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>10. Changes to the Terms</h2>
            <p>
              We may modify these Terms at any time. Any changes will be effective upon posting the revised Terms via
              the Services. Continued use of the Services constitutes acceptance of those changes.
            </p>
          </section>

          <section>
            <h2 className='mb-4 text-2xl font-semibold'>11. Contact Information</h2>
            <p>For any questions about these Terms, or to request account changes or data deletions, please contact:</p>
            <p className='mt-4'>
              Lucas
              <br />
              Email: lucas@superleader.ai
            </p>
          </section>

          <section className='mt-8 border-t pt-8'>
            <p className='text-gray-700'>
              By using SuperLeader, you acknowledge that you have read, understood, and agreed to be bound by these
              Terms of Service.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
