name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: test
    env:
      NEXT_PUBLIC_SUPABASE_URL: '${{ secrets.TEST_NEXT_PUBLIC_SUPABASE_URL }}'
      SUPABASE_SERVICE_ROLE_KEY: '${{ secrets.TEST_SUPABASE_SERVICE_ROLE_KEY }}'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn type-check

      - name: Run tests
        run: yarn test
